spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stmc_dev
    username: stmc_dev_user
    password: stmc
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true